Init
profcomff/userdata-api pull request #2
Opened 2023-04-10 17:33 UTC by grigoriev-semyon

2023-04-13 16:49 UTC, grigoriev-semyon commented
tests 93% lines

2023-04-13 17:18 UTC, Wudext requested changes
Переделай тесты с циклами и будет кайф

2023-04-13 17:18 UTC, Wudext commented on userdata_api/routes/base.py
> +app.include_router(user)
Разве инклюды не до middleware пишутся или плевать?

2023-04-13 17:18 UTC, Wudext commented on tests/test_routes/test_user.py
> +
Сделай цикл в test_get_no_all_scopes, test_get_a_few, test_get_a_few

2023-04-13 17:18 UTC, Wudext commented on userdata_api/schemas/source.py
> +    trust_level: conint(gt=1, lt=10) | None
Что за conint?

2023-04-13 20:34 UTC, grigoriev-semyon commented on userdata_api/schemas/source.py
> +    trust_level: conint(gt=1, lt=10) | None
Инт с ограничениями

2023-04-13 20:34 UTC, grigoriev-semyon commented on userdata_api/routes/base.py
> +app.include_router(user)
плевать

2023-04-15 14:39 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
@v4 + в шаблон

2023-04-15 14:40 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
@v4 + в шаблон

2023-04-15 14:40 UTC, grigoriev-semyon commented on .github/workflows/build_and_publish.yml
> +        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
бедный чел которого тегнули

2023-04-15 14:41 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
@v2 + в шаблон

2023-04-15 14:41 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: actions/checkout@master
@v3 + в шаблон

2023-04-15 14:42 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +      CONTAINER_NAME: com_profcomff_api_uerdata_test
TYPO

2023-04-15 14:42 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +            --env GUNICORN_CMD_ARGS='--log-config  logging_test.conf' \
Лишний пробел

2023-04-15 14:44 UTC, dyakovri commented on migrations/versions/9715ad3fa1d3_init.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Ты не отсмотрел миграции? Почему остался коммент "пожалуйста, скорректируйте"

2023-04-15 14:45 UTC, dyakovri commented on migrations/versions/9715ad3fa1d3_init.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Ты не отсмотрел миграции? Почему остался коммент "пожалуйста, скорректируйте"

2023-04-15 14:45 UTC, dyakovri commented on tests/conftest.py
> +    yield _random_string
Зачем так сложно? Почему не сделать random_string просто функцией в utils?

2023-04-15 14:47 UTC, dyakovri commented on tests/conftest.py
> +    yield client
Выполни https://github.com/profcomff/auth-lib/issues/14 и удали это чудо

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def category(dbsession, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def param(dbsession, category, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def source(dbsession, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def info(dbsession, source, param, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def category_no_scopes(dbsession, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def param_no_scopes(dbsession, category_no_scopes, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:49 UTC, dyakovri commented on tests/conftest.py
> +def info_no_scopes(dbsession, source, param_no_scopes, random_string):
Добавь комментарий что происходит, я не понимаю

2023-04-15 14:51 UTC, dyakovri commented on userdata_api/models/base.py
> +        """Get all objects with soft deletes"""
Не правда, объекты не отдает

2023-04-15 14:53 UTC, dyakovri commented on userdata_api/models/db.py
> +from __future__ import annotations
Опять устроил свалку из моделек в одном файле

2023-04-15 14:56 UTC, dyakovri commented on userdata_api/routes/__init__.py
> +from . import exc_handlers
Выглядит так себе, конечно
```python
import base
import exc_handlers
```

2023-04-15 14:59 UTC, dyakovri commented on userdata_api/routes/category.py
> +from userdata_api.schemas.user import refreshing
Мне не нравится локация файла, почему не в utils?

2023-04-15 15:00 UTC, dyakovri commented on userdata_api/routes/category.py
> +async def get_category(
А он не рефрешинг?

2023-04-15 15:00 UTC, dyakovri commented on userdata_api/routes/category.py
> +from userdata_api.schemas.user import refreshing
И докстринга не хватает

2023-04-15 15:00 UTC, dyakovri commented on userdata_api/routes/category.py
> +async def get_categories(
А он не рефрешинг?

2023-04-15 15:01 UTC, grigoriev-semyon commented on userdata_api/routes/category.py
> +async def get_category(
гет же

2023-04-15 15:01 UTC, dyakovri commented on userdata_api/routes/category.py
> +async def get_category(
Ааааа, походу рефрешинг – это тот, что изменяет

2023-04-15 15:02 UTC, dyakovri commented on userdata_api/routes/category.py
> +async def get_category(
Короч, докстрингу рефрешингу

2023-04-15 15:05 UTC, dyakovri commented on userdata_api/schemas/user.py
> +def refreshing(fn: Callable[P, Awaitable[T]]) -> Callable[P, Awaitable[T]]:
Докстрингу

2023-04-15 15:05 UTC, dyakovri commented on userdata_api/schemas/user.py
> +        await user_interface.refresh(db.session)
Кажется, меняться могут не только пользователи, но и категории

2023-04-15 15:06 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +        await user_interface.refresh(db.session)
к названию?

2023-04-15 19:38 UTC, grigoriev-semyon commented on .github/workflows/build_and_publish.yml
> +        uses: actions/checkout@master
а тут зачем?

2023-04-15 22:01 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +from __future__ import annotations
циклические импорты!

2023-04-15 22:01 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +from __future__ import annotations
это ж бд

2023-04-17 01:59 UTC, grigoriev-semyon commented on .github/workflows/build_and_publish.yml
> +        uses: actions/checkout@master
крч мастер оставлю

2023-04-17 02:05 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +        await user_interface.refresh(db.session)
не понял к чему коммент в общем
меняется только моделька /user/{user_id}
модельки категорий остаются

2023-04-18 16:52 UTC, grigoriev-semyon commented on tests/conftest.py
> +    yield client
готово

2023-04-19 09:54 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: actions/checkout@master
Потому что больше всего орет как раз на мастер. Там ветка уже сто лет как `main` называется

2023-04-19 09:55 UTC, dyakovri commented on .github/workflows/build_and_publish.yml
> +        uses: actions/checkout@master
Поставь версию, чтоб не было спецэффектов

2023-04-19 09:55 UTC, dyakovri commented on .github/workflows/tests.yml
> +      - uses: actions/checkout@mastre
Мастрэ
Версию три, пожалуйста

2023-04-19 09:56 UTC, dyakovri commented on userdata_api/schemas/user.py
> +    Декоратор для обертки функций обновляющих модель ответа `GET /user/{user_id}`
А зачем он мне, этот декоратор?

2023-04-19 09:57 UTC, dyakovri commented on userdata_api/schemas/user.py
> +        await user_interface.refresh(db.session)
А почему модельки категорий остаются? В категории же могут появляться новые поля

2023-04-19 09:57 UTC, dyakovri commented on userdata_api/utils/utils.py
> +    return "".join([random.choice(string.ascii_lowercase) for _ in range(length)])
Форматирование

2023-04-19 09:59 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +        await user_interface.refresh(db.session)
в модели категорий - нет
только одна модель меняется

2023-04-19 12:49 UTC, dyakovri commented on userdata_api/models/db.py
> +from __future__ import annotations
> циклические импорты!

Там почти всегда можно заменить класс на название таблицы в строке

2023-04-19 13:12 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +from __future__ import annotations
Тайп хинты не поменяешь

2023-04-19 13:12 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +from __future__ import annotations
я уже пробовал

2023-04-19 15:00 UTC, dyakovri commented on tests/conftest.py
> +    Вызов создает категорию с двумя рандомными скоупами и возвращщает ее
Вызов фикстуры или вызов фабрики? А вызов фабрики что делает? А почему рандомными, а не заданными параметром? А как пользоваться?

И для всех остальных фикстур то же самое

2023-04-19 15:29 UTC, dyakovri requested changes
Очень тяжело осознать что за сущности за что отвечают, какая между ними иерархия. info, category, param. Нужна схема или описание в ридми. И Кажется, у тебя все ручки плоские, но я ожидаю, что параметры находятся внутри категорий

А еще про разделение доступов к категориям, кажется, ты забыл

2023-04-19 15:29 UTC, dyakovri commented on tests/test_routes/test_category.py
> +    assert response.status_code == 404
Вижу тут использование `.get`, не нужен `userdata.category.read`?

2023-04-19 15:29 UTC, dyakovri commented on tests/conftest.py
> +    yield TestClient(app)
Почему с андерскором?

2023-04-19 15:29 UTC, dyakovri commented on tests/test_routes/test_param.py
> +    assert query2
Есть геттер, нет скоупа

2023-04-19 15:29 UTC, dyakovri commented on tests/test_routes/test_info.py
> +    assert q
Есть геттер, не скоупа

2023-04-19 15:29 UTC, dyakovri commented on tests/test_routes/test_info.py
> +    response = _client.patch(f"/info/{_info.id}", json={"value": f"{_info.value}updated"})
Есть патч, нет скоупа

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/category.py
> +    return parse_obj_as(list[CategoryGet], result)
Нужна ли эта ручка? Эта же информация отдается при гет запросе пользователя

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +    return parse_obj_as(list[InfoGet], Info.query(session=db.session).all())
Нужна ли эта ручка, есть же get запрос категории

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +        "userinfo.info.delete" not in [scope["name"] for scope in user["session_scopes"]]
Если ты в 99% случаев пользуешься скоупами в виде листа строк, то стоит эту логику вынести в аутх-либ

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +        and user["user_id"] != info.owner_id
Правда ли, что пользователь всегда может удалить любую информацию о себе? Мне не нравится

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +        and user["user_id"] != info.owner_id
Давай только ту, что создал сам пользователь

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +    Info.delete(id, session=db.session)
Я тут вообще не вижу логики работы с сорсом. Если пользователь изменяет информацию о себе, а до этого была информация из ВК, то создается новая запись с ручным сорсом

В геттерах забирается та запись, где у сорса самое высокое значение доверия

Как разграничивается редактирование себя и редактирование админом другого пользователя? Админский сорс всегда самый приоритетный

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/param.py
> +param = APIRouter(prefix="/param", tags=["Param"])
Разве параметр не принадлежит категории?

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/param.py
> +    return ParamGet.from_orm(Param.create(session=db.session, **param_inp.dict()))
Если я создаю в категории параметр, то док категории должен обновиться?

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/info.py
> +    return parse_obj_as(list[InfoGet], Info.query(session=db.session).all())
А, оба геттера немножко бесполезные. Оставь только `GET /user/{id}`

2023-04-19 15:29 UTC, dyakovri commented on userdata_api/routes/user.py
> +    return Response(content=json.dumps(res), media_type="application/json")
У категорий же есть скоупы. Как быть уверенным, что Иван Иванович, запросив данные Василия Пупкина, не получит его токены к гуглу?

2023-04-20 01:05 UTC, grigoriev-semyon commented on userdata_api/routes/info.py
> +        and user["user_id"] != info.owner_id
> Давай только ту, что создал сам пользователь

это будет сложно
овнер - всегда юзер, кто там создал ее - не важно

2023-04-20 01:13 UTC, grigoriev-semyon commented on userdata_api/routes/info.py
> +        and user["user_id"] != info.owner_id
можно использовать для этого changeable

2023-04-21 14:23 UTC, grigoriev-semyon commented on userdata_api/routes/info.py
> +        "userinfo.info.delete" not in [scope["name"] for scope in user["session_scopes"]]
создал тикет

2023-04-21 17:55 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +    return ParamGet.from_orm(Param.create(session=db.session, **param_inp.dict()))
док ответа должен да

2023-04-21 17:56 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +    return ParamGet.from_orm(Param.create(session=db.session, **param_inp.dict()))
док ответа на юзера

2023-04-21 18:20 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    return Response(content=json.dumps(res), media_type="application/json")
там все обрабатывается в get_user_info_func

2023-04-21 18:22 UTC, grigoriev-semyon commented on userdata_api/routes/info.py
> +    Info.delete(id, session=db.session)
ну можно поставить значение доверия сорсу просто высокое если это админ редачит

2023-04-22 00:35 UTC, grigoriev-semyon commented on userdata_api/routes/category.py
> +    return parse_obj_as(list[CategoryGet], result)
не полностью 
там отдается только то на что есть права

2023-04-22 00:42 UTC, grigoriev-semyon commented on userdata_api/routes/info.py
> +        and user["user_id"] != info.owner_id
добавил 
+2 теста

2023-05-04 19:03 UTC, dyakovri commented on migrations/versions/868f53d699b7_init.py
> +    # ### commands auto generated by Alembic - please adjust! ###
💩

2023-05-04 19:57 UTC, dyakovri reviewed
Я пока устал, второй подход через полчасика

2023-05-04 19:57 UTC, dyakovri commented on tests/conftest.py
> +    ```
Закрывающие без открывающих, прикол)

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/base.py
> +        attr_names = [c_attr.key for c_attr in inst.mapper.column_attrs]
[Table.columns](https://docs.sqlalchemy.org/en/20/core/metadata.html#sqlalchemy.schema.Table)

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/base.py
>  from sqlalchemy.ext.declarative import as_declarative, declared_attr
MovedIn20Warning: The ``as_declarative()`` function is now available as sqlalchemy.orm.as_declarative() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

declared_attr туда же

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/base.py
> +        attr_names = [c_attr.key for c_attr in inst.mapper.column_attrs]
Тем более функция inspect не работает, если объект еще не в БД

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/base.py
> +        attr_names = [c_attr.key for c_attr in inst.mapper.column_attrs]
`list(self.__table__.columns.keys())`

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/base.py
> +                continue
`for i in self.__table__.columns.keys()`?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +class Type(str, Enum):
Нейминг ну такое. Давай что-нибудь более внятное 
Тип выдачи параметра?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +    type: Mapped[Type] = mapped_column(DbEnum(Type, native_enum=False), nullable=True)
Почему nullable?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +    infos: Mapped[Info] = relationship(
values?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +                return list[str]
Четверная вложенность вместо тернара?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +class Source(BaseDbModel):
```python
create_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
modify_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
```

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +class Param(BaseDbModel):
```python
create_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
modify_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
```

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/models/db.py
> +class Category(BaseDbModel):
```python
create_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
modify_ts: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
```

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/routes/base.py
> +    )
Что изменил и зачем? Желательно в докстрингу дописать заодно

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/routes/base.py
> +    )
Напомню, что на проде у нас юзается другой сваггер

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/routes/base.py
> +app.add_route(app.docs_url, swagger_ui_html, include_in_schema=False)
Почему не `@app.get` в декораторе?

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/routes/base.py
> +async def get_docs(request: Request):
Желательно в докстрингу дописать зачем

2023-05-04 19:57 UTC, dyakovri commented on userdata_api/routes/base.py
> +        await user_interface.refresh(db.session)
Желательно в докстрингу дописать зачем

2023-05-04 20:41 UTC, dyakovri commented on userdata_api/schemas/types/scope.py
> +    __weakref__ = property(lambda self: object(), lambda self, v: None, lambda self: None)
Зачем? Комментом

2023-05-04 20:43 UTC, dyakovri commented on userdata_api/schemas/user.py
> +    UserUpdate: type[Base] = create_model("UserUpdate", __base__=Base)
Не увидел чтоб использовались

2023-05-04 20:51 UTC, dyakovri commented on userdata_api/schemas/user.py
> +class UserInterface:
Не, без 100 грамм и докстринга не разберешь......

2023-05-04 21:03 UTC, dyakovri reviewed
Остальное завтра

2023-05-04 21:03 UTC, dyakovri commented on userdata_api/utils/docs.py
> +async def aio_get_openapi(request: Request) -> dict[str, Any]:
А чо генератор доки тут, а генератор сваггера не тут?

2023-05-04 21:03 UTC, dyakovri commented on userdata_api/routes/user.py
> +    id: int, user: dict[str, Any] = Depends(UnionAuth(scopes=[], allow_none=False, auto_error=True))
allow_none=False, auto_error=True – это же умолчания

2023-05-04 21:03 UTC, dyakovri commented on userdata_api/routes/user.py
> +    id: int, user: dict[str, Any] = Depends(UnionAuth(scopes=[], allow_none=False, auto_error=True))
Кстати, кажется, они тебе не подходят

2023-05-05 21:55 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +    UserUpdate: type[Base] = create_model("UserUpdate", __base__=Base)
это создание первичных ссылок

2023-05-05 23:20 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    id: int, user: dict[str, Any] = Depends(UnionAuth(scopes=[], allow_none=False, auto_error=True))
Почему не подходят?

2023-05-19 22:27 UTC, Temmmmmo commented on migrations/versions/f8c57101c0f6_init.py
> +    # ### commands auto generated by Alembic - please adjust! ###
Комменты удали)

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/routes/category.py
> +    return None
Лучше, чтобы StatusResponseModel возвращала, я думаю

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/routes/exc_handlers.py
> +
Почему для AlreadyExists нет хэндлера?

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/routes/param.py
> +async def delete_param(
Пусть StatusResponseModel возвращается

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/routes/source.py
> +) -> None:
StatusResponseModel

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/routes/user.py
> +):
Type-hint на возвращаемое значение?

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/schemas/category.py
> +    name: constr(min_length=1)
Почему тут name не может быть None...

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/schemas/category.py
> +    name: constr(min_length=1) | None
...а тут может

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +    scope_names = tuple(scope["name"] for scope in user["session_scopes"])
Зачем кортеж?

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +    db.session.flush()
db.session.commit() еще, нет?

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +        info_filter.extend([param.id for param in category.params])
Зачем extend, если у тебя info_filter всегда перед этим пустой? Можно сразу `info_filter = list(i for i in ...)`

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +        info_map[(info.param.id, info.source_id)] = info
info, info, info... читаемость на уровне(нет)

2023-05-19 22:27 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +    scope_names = tuple(scope["name"] for scope in user["session_scopes"])
Не совсем пойму опять, зачем тут кортеж?  Меньше памяти занимает, чем лист, только из-за этого?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/routes/base.py
>      root_path=settings.ROOT_PATH if __version__ != 'dev' else '/',
как это работает?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/routes/category.py
> +    return parse_obj_as(list[CategoryGet], Category.query(session=db.session).all())
Что за parse_obj_as ?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/schemas/types/scope.py
> +        if len(set(val) - set(string.ascii_lowercase + "._")) > 0:
Что эта проверка делает? `len(set(val) - set(string.ascii_lowercase + "._"))`

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/schemas/user.py
> +        origin_model.__annotations__ = deepcopy(annotations)
`deepcopy` это что?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/utils/docs.py
> +    return await loop.run_in_executor(thread_pool, partial(get_openapi, **kwargs))
`loop.run_in_executor(thread_pool, partial(get_openapi, **kwargs))` что это?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/utils/user_get.py
> +                .order_by(Info.modify_ts.desc())
`desc()` ?

2023-05-19 22:51 UTC, Temmmmmo commented on userdata_api/utils/user_get.py
> +    @wraps(fn)
`@wraps(fn)` ?

2023-05-19 23:05 UTC, Temmmmmo commented on migrations/versions/f8c57101c0f6_init.py
> +        sa.Column('create_ts', sa.DateTime(), nullable=False),
То, что nullable=False, надо, наверное, запрос в базу кинуть и проставить туда current_timestamp, а потом сделать nullable=True

2023-05-19 23:05 UTC, Temmmmmo commented on userdata_api/routes/param.py
> +    return ParamGet.from_orm(Param.update(id, session=db.session, **param_inp.dict(exclude_unset=True)))
`from_orm()` ?

2023-05-19 23:05 UTC, Temmmmmo commented on userdata_api/routes/source.py
> +    :return: SourceGet - созданныый источник
Ошибка орфографическая в комменте)

2023-05-19 23:05 UTC, Temmmmmo commented on userdata_api/schemas/source.py
> +    trust_level: conint(gt=0, lt=11) | None
`conint(gt=0, lt=11)` ?

2023-05-19 23:05 UTC, Temmmmmo commented on userdata_api/utils/user_post.py
> +        return
а так можно ничего не возвращать?

2023-05-19 23:05 UTC, Temmmmmo commented on userdata_api/utils/user_get.py
> +P = ParamSpec("P")
зачем так делать?

2023-05-19 23:09 UTC, grigoriev-semyon commented on userdata_api/schemas/category.py
> +    name: constr(min_length=1) | None
Потому что если ты не хочешь патчить то просто не указываешь имя
А создать без имени никак

2023-05-19 23:09 UTC, grigoriev-semyon commented on userdata_api/utils/user_post.py
> +    scope_names = tuple(scope["name"] for scope in user["session_scopes"])
А есть варианты получше?

2023-05-19 23:09 UTC, grigoriev-semyon commented on userdata_api/utils/user_post.py
> +    db.session.flush()
Автокоммит

2023-05-19 23:10 UTC, grigoriev-semyon commented on userdata_api/utils/user_post.py
> +        info_filter.extend([param.id for param in category.params])
Он меняется в цикле же
На первой итерации только пустой

2023-05-19 23:11 UTC, grigoriev-semyon commented on userdata_api/utils/user_post.py
> +    scope_names = tuple(scope["name"] for scope in user["session_scopes"])
Доступ побыстрее еще 
Но вообще это несущественно
Просто хочу кортеж

2023-05-19 23:13 UTC, grigoriev-semyon commented on userdata_api/routes/category.py
> +    return parse_obj_as(list[CategoryGet], Category.query(session=db.session).all())
Спарсить объект как 
Нужно чтобы не создавать много типов данных

2023-05-19 23:15 UTC, grigoriev-semyon commented on userdata_api/schemas/types/scope.py
> +        if len(set(val) - set(string.ascii_lowercase + "._")) > 0:
Проверяет что в строке скоупа только аски символы и вон те еще два 
Нижнее подч и точка 

Ну разность множеств нулевое множество будет просто если скоуп норм

2023-05-19 23:15 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +        origin_model.__annotations__ = deepcopy(annotations)
Рекурсивное копирование объекта 
Почитай доку лучше тут
Оно тут надо чтобы ссылки не менять на изначальные модельки

2023-05-19 23:17 UTC, grigoriev-semyon commented on userdata_api/utils/docs.py
> +    return await loop.run_in_executor(thread_pool, partial(get_openapi, **kwargs))
Запустить функцию в тредпуле))
Это костыльная асинхронность

2023-05-19 23:17 UTC, grigoriev-semyon commented on userdata_api/utils/user_get.py
> +                .order_by(Info.modify_ts.desc())
По убыванию

2023-05-19 23:18 UTC, grigoriev-semyon commented on userdata_api/utils/user_get.py
> +    @wraps(fn)
Сохраняет сигнатуру оборачиваемой функции 
Ведь иначе там арги и кварги а надо чтобы имя сохранилось, тайп хинты и все дела
Это ж штука которая вернет функцию которая потом оборачивается в ручку фастапи

2023-05-19 23:19 UTC, grigoriev-semyon commented on migrations/versions/f8c57101c0f6_init.py
> +        sa.Column('create_ts', sa.DateTime(), nullable=False),
База пустая) это первая миграция

2023-05-19 23:20 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +    return ParamGet.from_orm(Param.update(id, session=db.session, **param_inp.dict(exclude_unset=True)))
Парсит инстансы классов алхимии 

Так то классу в ините нужен распакованный словарь а в алхимии с этим сложно хоть я и написал эту функциональность туда

2023-05-19 23:21 UTC, grigoriev-semyon commented on userdata_api/schemas/source.py
> +    trust_level: conint(gt=0, lt=11) | None
Это фабрика классов которая возвращает класс пайдентика с соотв ограничениями 
Типа от 1 до 11 число

2023-05-19 23:21 UTC, grigoriev-semyon commented on userdata_api/utils/user_post.py
> +        return
Да

2023-05-19 23:22 UTC, grigoriev-semyon commented on userdata_api/utils/user_get.py
> +P = ParamSpec("P")
Просто дженерики
Я ж общий декоратор пишу

2023-05-22 17:54 UTC, grigoriev-semyon commented on userdata_api/routes/base.py
>      root_path=settings.ROOT_PATH if __version__ != 'dev' else '/',
просто отключает доку стандартную
а нас на севрере свой сваггер стоит, который агрегирует доку

2023-07-02 17:03 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +):
здесь не надо

2023-07-02 17:18 UTC, merged