14 скрытие части юзердаты от пользователя
profcomff/userdata-api pull request #23
Opened 2024-04-02 21:11 UTC by gitfresnel

## Изменения
Изменил класс Param и ручку param.get
## Детали реализации
Добавил в класс Param поле is_hidden (по умолчанию True = скрыт). 
Ручка param.get теперь работает следующим образом: 
1. проводим обязательную авторизацию (но скупы при этом не нужны), чтобы узнать скоупы пользователя 
2. достаём параметр по айди и проверяем флаг скрытости
3. если он установлен в True, то достаём скоупы на чтение категории, скоупы юзера и ищем их разность
4. если разность пустая, значит у пользователя есть скоупы и мы возвращаем ему параметр. Наоборот - возбуждаем ошибку

Пока я не тестил работу ручки, ибо затуп был  лютый с аутентификацией и базой данных 
## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-04-03 21:36 UTC, grigoriev-semyon requested changes

2024-04-03 21:36 UTC, grigoriev-semyon commented on requirements.txt
> +fastapi==0.100.1
мы не фиксируем версии

2024-04-03 21:36 UTC, grigoriev-semyon commented on requirements.txt
> +uvicorn==0.23.1
то же самое

2024-04-03 21:36 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +    is_hidden: Mapped[bool] = mapped_column(Boolean, default=True)
default=False лучше
Там очень мало чего придется скрывать

2024-04-03 21:36 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +        return ParamGet.model_validate(res)
read_scope немного про другое
В целом тут не сильно нужно пока что проверять какие то скоупы
Пока что можно просто сделать is_hidden, если True - то не отдавать
Потом прикрутим скоупы уже

2024-04-03 21:36 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +) -> ParamGet:
это не та ручка
тут как раз надо отдавать is_hidden тк здесь нет никакой пользовательской инфы
тебе нужно менять utils/user/get_user_info

2024-04-03 21:36 UTC, grigoriev-semyon commented on userdata_api/routes/param.py
> +) -> ParamGet:
см https://github.com/profcomff/userdata-api/issues/14#issuecomment-2035640012

2024-04-03 21:37 UTC, grigoriev-semyon commented on userdata_api/models/db.py
> +    is_hidden: Mapped[bool] = mapped_column(Boolean, default=True)
переименуй как в комменте https://github.com/profcomff/userdata-api/issues/14#issuecomment-2035640012

2024-07-21 18:18 UTC, Temmmmmo commented on .idea/.gitignore
Кажется .idea не нужен

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/routes/user.py
> +    additional_data: list[str] = Query(default=[]),
Не совсем пойму, зачем тут новый аргумент? Нужно было просто изменить UserInfoGet

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/schemas/param.py
> +    visible_in_user_response: bool = True
давай просто visible

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/schemas/param.py
> +    visible_in_user_response: bool = True
visible

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +    :additional_data: Список невидимых по дефолту параметров
здесь тоже не надо, просто в модельку параметра надо было добавить visible и все. иначе это не будет работать, так как, чтобы получить информацию о юзере, ты запрашиваешь уже часть этой информации в запрос

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/schemas/param.py
> +    visible_in_user_response: bool = True
еще надо это все поддержать в ручках параметров, чтобы там вообще можно было добавить это поле

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +        .filter(
здесь ты не реализовал проверку на наличие скоупов у юзера для чтения, задумка есть, но это не то
нужно было использовать AuthLib или AuthAPI на крайняк...

2024-07-21 18:18 UTC, Temmmmmo commented on userdata_api/schemas/param.py
> +    visible_in_user_response: bool = True
просто сейчас по факту, ты даже не можешь в параметр это поле толком добавить, тогда смысл от этого всего

2024-08-13 16:20 UTC, Temmmmmo reviewed
Так, короче, давай откатим коммит, потому что я только сейчас увидел коммент Семена апрельский, где он говорил добавлять Query-параметр
Мне это показалось странным, так как не совпадало с изначальным ТЗ
Можешь просто откатить, по идее, коммит, и запросить мое ревью
Прошу прощения

2024-09-11 14:08 UTC, Temmmmmo commented
убери idea из коммента

2024-09-19 11:52 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +    additional_data: list[str],
сделай list[int], а лучше set, но, я не уверен, что set тут может быть, поэтому сделай лист, потом приведи к set

2024-09-19 11:52 UTC, Temmmmmo commented on userdata_api/routes/user.py
> +    additional_data: list[str] = Query(default=[]),
тут тоже лист из интов

2024-09-21 17:34 UTC, Temmmmmo commented on userdata_api/schemas/types/scope.py
> +    def __get_pydantic_core_schema__(cls, source: type[Any], handler: Callable) -> core_schema.CoreSchema:
```
from pydantic import GetCoreSchemaHandler, TypeAdapter


class Username(str):
    @classmethod
    def __get_pydantic_core_schema__(
        cls, source_type: Any, handler: GetCoreSchemaHandler
    ) -> CoreSchema:
        return core_schema.no_info_after_validator_function(cls, handler(str))
```

2024-09-21 17:34 UTC, Temmmmmo commented on userdata_api/schemas/types/scope.py
> +    def __get_pydantic_core_schema__(cls, source: type[Any], handler: Callable) -> core_schema.CoreSchema:
нужно использовать тип GetCoreSchemaHandler а не Callable

2024-09-27 17:43 UTC, DaymasS requested changes

2024-09-27 17:43 UTC, DaymasS commented on userdata_api/schemas/types/scope.py
> +from typing import Any, Callable
Импорт Callable здесь больше не нужен

2024-09-27 17:43 UTC, DaymasS commented on userdata_api/schemas/types/scope.py
> +from pydantic import GetCoreSchemaHandler
Можешь по аналогии импортировать GetJsonSchemaHandler из pydantic; удалить импорт на 5 строке и в 25 строке удалить _schema_generation_shared.

Для того чтобы 
GetJsonSchemaHandler импортировался глобально из pydantic, а не через файл pydantic._internal

2024-10-04 12:33 UTC, Temmmmmo approved these changes

2024-10-05 17:11 UTC, DaymasS approved these changes

2024-10-23 13:16 UTC, merged