добавление ручки для получения данных обо всех пользователях
profcomff/userdata-api pull request #41
Opened 2024-07-16 11:15 UTC by Zimovchik

## Изменения

## Детали реализации

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-07-17 15:15 UTC, grigoriev-semyon requested changes

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    categories: list[str] = Query(),
имелось ввиду что там будет список id

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    Если не указать users и categories, то вернется информация обо всех пользователях
вроде договорились что нет

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    :return: словарь, где ключь - id пользователя, значение - информация.
ключ

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            ),
если будет список id то это не надо

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            ),
только in останется

2024-07-17 15:15 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +        if info.category.read_scope and info.category.read_scope not in scope_names and user["id"] != info.owner_id:
здесь не надо проверять ownerство потому что ручка чисто для админов

2024-07-18 08:46 UTC, Zimovchik commented on userdata_api/routes/user.py
> +    Если не указать users и categories, то вернется информация обо всех пользователях
ага, забыл убрать из доки, функционала уже не было

2024-07-29 09:25 UTC, grigoriev-semyon requested changes

2024-07-29 09:25 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +from userdata_api.models.db import *
так лучше не делать

2024-07-29 09:25 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +from userdata_api.models.db import *
надо конкретные имена импортить

2024-07-29 09:25 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +    assert not (
item __not in__ iterable

2024-07-29 09:25 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +    assert not (
везде где такое есть поправь

2024-07-29 09:25 UTC, grigoriev-semyon commented on userdata_api/schemas/user.py
> +    users: dict[int, UserInfoGet] | None = None
почему дефолт None?

2024-07-29 09:25 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +        response.json()["users"]["1"]["items"]
не очень понял почему 1 - это строка
и почему user_id в этом джсоне получился строкой вообще?

2024-08-12 07:58 UTC, grigoriev-semyon requested changes

2024-08-12 07:58 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            and (info.owner_id != user["id"] if is_single_user else True)
Нечитаемо, разверни без тернарника

2024-08-12 07:58 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +from sqlalchemy import and_, not_, or_
Используется?

2024-08-12 09:26 UTC, grigoriev-semyon requested changes

2024-08-12 09:26 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +    print(client.get(f"/user", params={"users": [2, 1], "categories": [category1.id]}).json())
такое нам не надо

2024-08-12 09:26 UTC, grigoriev-semyon commented on tests/test_routes/test_users_get.py
> +    print(response.json())
и такое

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/routes/user.py
> +    :return: список данных о пользователях и данных категориях в формате {user_id: user_id, category: category_name, param: param_name, value: value}
формат не надо писать, моделька же есть

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +    :return: Список словарей содержащих id пользователя(только если берем информацию о нескольких пользователях), категорию, параметр категории и значение этого параметра у пользователя
устарела инфа

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            and (info.owner_id != user["id"] or not is_single_user)
я бы переставил эти условия местами

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            param_dict[info.param][info.owner_id] = info
тут раньше был коммент, надо вернуть

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +    for param, owner_dict in param_dict.items():
user_dict тогда уж а не owner

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            param_dict[info.param][info.owner_id] = [] if is_many_values else None
`if info.param.type == ViewType.ALL`
is_many_values удали тогда

2024-08-12 09:26 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +) -> list[dict]:
dict[?, ?]

2024-08-12 11:27 UTC, grigoriev-semyon approved these changes

2024-08-12 11:59 UTC, merged