Add validation field to param
profcomff/userdata-api pull request #42
Opened 2024-07-25 06:06 UTC by DaymasS

## Изменения
Добавлена валидация данных в юзер дате и тесты к ней

## Детали реализации
У таблицы Param появилось новое поле validation - строка - нулабл

При заполнении этой строки происходит проверка компилируемости полученного регулярного выражения. При ошибке возвращается код 422 Invalid argument. 

Далее при попытке обновить или создать параметр с не нулевым полем валидации у какого либо юзера будет происходить сравнение нового значения параметра с регулярным выражением. При ошибке возвращается код 422 Invalid argument.

## Check-List

- [ ] Вы проверили свой код перед отправкой запроса?
- [ ] Вы написали тесты к реализованным функциям?
- [ ] Вы не забыли применить форматирование `black` и `isort` для _Back-End_ или `Prettier` для _Front-End_?

2024-08-13 16:32 UTC, Temmmmmo commented on userdata_api/routes/exc_handlers.py
> +async def already_exists_handler(req: starlette.requests.Request, exc: InvalidArgument):
название функции поменяй)

2024-08-13 16:32 UTC, Temmmmmo commented on userdata_api/routes/exc_handlers.py
> +@app.exception_handler(InvalidArgument)
Назови лучше InvalidValidation

2024-08-13 16:32 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +        else:
давай без else
сделай, как было раньше

2024-08-13 16:32 UTC, Temmmmmo commented on userdata_api/utils/user.py
> -        if item.value is None:
здесь можно вообще убрать это иф, так как там continue

2024-08-13 16:32 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +            if param.validation and search(param.validation, item.value) is None:
`if param.validation is not None`

2024-08-15 08:06 UTC, DaymasS commented on userdata_api/routes/exc_handlers.py
> +@app.exception_handler(InvalidArgument)
В таком случае придётся добавить ещё одно исключение для не компилируемой регулярки

2024-08-19 16:24 UTC, Temmmmmo approved these changes

2024-08-19 16:27 UTC, Temmmmmo requested changes

2024-08-19 16:27 UTC, Temmmmmo commented on userdata_api/utils/user.py
>          if item.value is None:
я про другой иф говорил, в  103 строке... (ПС теперь в 96), т.е. проверка на нан
просто убрать иф, а все, что под ним -4 пробела

2024-08-19 16:28 UTC, Temmmmmo commented on userdata_api/routes/exc_handlers.py
> +@app.exception_handler(InvalidArgument)
пусть так

2024-08-22 13:50 UTC, Temmmmmo approved these changes

2024-08-22 16:00 UTC, merged