Userdata fixes.
profcomff/userdata-api pull request #8
Opened 2023-07-28 18:24 UTC by Temmmmmo

## Изменения
Пофикшены некоторые баги в ручках юзера.

## Детали
Изменены ключи словарей и добавлена проверка на None для скоупов.

## Check-List
- [x] Вы проверили свой код перед отправкой запроса?
- [x] Вы написали тесты к реализованным функциям?
- [x] Вы не забыли применить black и isort?

2023-07-28 21:14 UTC, grigoriev-semyon requested changes

2023-07-28 21:14 UTC, grigoriev-semyon commented on userdata_api/utils/user.py
> +            and param.category.update_scope is not None
Эта строка должна быть первая

2023-07-29 14:08 UTC, Temmmmmo commented on userdata_api/utils/user.py
> +            and param.category.update_scope is not None
исправил с телефона

2023-07-29 14:09 UTC, grigoriev-semyon approved these changes

2023-07-29 14:09 UTC, merged